[package]
edition.workspace = true
name = "config_analyzer_service"
publish.workspace = true
rust-version.workspace = true
version = "0.1.0"

[[bin]]
name = "config-analyzer-service"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
config_analyzer_core = { workspace = true }
config_analyzer_loader = { workspace = true }
config_analyzer_perfetto = { workspace = true }
config_analyzer_pipeline_manager = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true